/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_physfs_PhysFSWrapper */

#ifndef _Included_com_physfs_PhysFSWrapper
#define _Included_com_physfs_PhysFSWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_physfs_PhysFSWrapper
 * Method:    PHYSFS_set_dirs
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_physfs_PhysFSWrapper_setDirs
  (JNIEnv *, jobject, jstring, jstring);
  
  JNIEXPORT void JNICALL Java_com_physfs_PhysFSWrapper_test
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
